# Form implementation generated from reading ui file '/home/addinedu/dev/roscamp-repo-1/ros2_ws/src/shopee_app/ui/layout_admin.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form_admin(object):
    def setupUi(self, Form_admin):
        Form_admin.setObjectName("Form_admin")
        Form_admin.resize(1266, 758)
        self.gridLayout = QtWidgets.QGridLayout(Form_admin)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.side_bar = QtWidgets.QWidget(parent=Form_admin)
        self.side_bar.setObjectName("side_bar")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.side_bar)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.side_bar)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.gridLayout.addWidget(self.side_bar, 1, 0, 1, 1)
        self.logo_area = QtWidgets.QWidget(parent=Form_admin)
        self.logo_area.setObjectName("logo_area")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.logo_area)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_to_login = QtWidgets.QPushButton(parent=self.logo_area)
        self.btn_to_login.setObjectName("btn_to_login")
        self.horizontalLayout.addWidget(self.btn_to_login)
        self.gridLayout.addWidget(self.logo_area, 0, 0, 1, 1)
        self.top_bar = QtWidgets.QWidget(parent=Form_admin)
        self.top_bar.setObjectName("top_bar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.top_bar)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.top_bar)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.gridLayout.addWidget(self.top_bar, 0, 1, 1, 1)
        self.stack_content = QtWidgets.QStackedWidget(parent=Form_admin)
        self.stack_content.setObjectName("stack_content")
        self.stackedWidget_3Page1 = QtWidgets.QWidget()
        self.stackedWidget_3Page1.setObjectName("stackedWidget_3Page1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.stackedWidget_3Page1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(parent=self.stackedWidget_3Page1)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.stack_content.addWidget(self.stackedWidget_3Page1)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stack_content.addWidget(self.page)
        self.gridLayout.addWidget(self.stack_content, 1, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 8)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 10)

        self.retranslateUi(Form_admin)
        QtCore.QMetaObject.connectSlotsByName(Form_admin)

    def retranslateUi(self, Form_admin):
        _translate = QtCore.QCoreApplication.translate
        Form_admin.setWindowTitle(_translate("Form_admin", "Form"))
        self.label.setText(_translate("Form_admin", "관리자 사이드바"))
        self.btn_to_login.setText(_translate("Form_admin", "로그인 화면"))
        self.label_2.setText(_translate("Form_admin", "관리자 탑바"))
        self.pushButton.setText(_translate("Form_admin", "PushButton"))
