# Form implementation generated from reading ui file '/home/addinedu/dev/roscamp-repo-1/shopee_ros2/src/shopee_app/shopee_app/ui/cart_select_item.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_cart_select_item(object):
    def setupUi(self, cart_select_item):
        cart_select_item.setObjectName("cart_select_item")
        cart_select_item.resize(903, 300)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(cart_select_item)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.item_image = QtWidgets.QLabel(parent=cart_select_item)
        self.item_image.setObjectName("item_image")
        self.horizontalLayout_2.addWidget(self.item_image)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.item_name = QtWidgets.QLabel(parent=cart_select_item)
        self.item_name.setWordWrap(True)
        self.item_name.setObjectName("item_name")
        self.verticalLayout.addWidget(self.item_name)
        self.item_count = QtWidgets.QLabel(parent=cart_select_item)
        self.item_count.setObjectName("item_count")
        self.verticalLayout.addWidget(self.item_count)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.item_state = QtWidgets.QLabel(parent=cart_select_item)
        self.item_state.setObjectName("item_state")
        self.horizontalLayout_2.addWidget(self.item_state)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 3)
        self.horizontalLayout_2.setStretch(2, 1)

        self.retranslateUi(cart_select_item)
        QtCore.QMetaObject.connectSlotsByName(cart_select_item)

    def retranslateUi(self, cart_select_item):
        _translate = QtCore.QCoreApplication.translate
        cart_select_item.setWindowTitle(_translate("cart_select_item", "Form"))
        self.item_image.setText(_translate("cart_select_item", "상품이미지"))
        self.item_name.setText(_translate("cart_select_item", "신선식품 무농약 양상추"))
        self.item_count.setText(_translate("cart_select_item", "(1/1)"))
        self.item_state.setText(_translate("cart_select_item", "진행중"))
