# Form implementation generated from reading ui file '/home/addinedu/dev/roscamp-repo-1/shopee_ros2/src/shopee_app/shopee_app/ui/cart_item.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CartItemWidget(object):
    def setupUi(self, CartItemWidget):
        CartItemWidget.setObjectName("CartItemWidget")
        CartItemWidget.resize(887, 254)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(CartItemWidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.chk_selected = QtWidgets.QCheckBox(parent=CartItemWidget)
        self.chk_selected.setText("")
        self.chk_selected.setObjectName("chk_selected")
        self.horizontalLayout_2.addWidget(self.chk_selected)
        self.label_image = QtWidgets.QLabel(parent=CartItemWidget)
        self.label_image.setObjectName("label_image")
        self.horizontalLayout_2.addWidget(self.label_image)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_name = QtWidgets.QLabel(parent=CartItemWidget)
        self.label_name.setObjectName("label_name")
        self.verticalLayout.addWidget(self.label_name)
        self.label_price = QtWidgets.QLabel(parent=CartItemWidget)
        self.label_price.setObjectName("label_price")
        self.verticalLayout.addWidget(self.label_price)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_increase = QtWidgets.QToolButton(parent=CartItemWidget)
        self.btn_increase.setObjectName("btn_increase")
        self.horizontalLayout.addWidget(self.btn_increase)
        self.edit_quantity = QtWidgets.QLineEdit(parent=CartItemWidget)
        self.edit_quantity.setObjectName("edit_quantity")
        self.horizontalLayout.addWidget(self.edit_quantity)
        self.btn_decrease = QtWidgets.QToolButton(parent=CartItemWidget)
        self.btn_decrease.setObjectName("btn_decrease")
        self.horizontalLayout.addWidget(self.btn_decrease)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_total_price = QtWidgets.QLabel(parent=CartItemWidget)
        self.label_total_price.setObjectName("label_total_price")
        self.verticalLayout.addWidget(self.label_total_price)
        self.verticalLayout.setStretch(0, 3)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 3)
        self.verticalLayout.setStretch(3, 3)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btn_delete = QtWidgets.QToolButton(parent=CartItemWidget)
        self.btn_delete.setObjectName("btn_delete")
        self.horizontalLayout_2.addWidget(self.btn_delete)

        self.retranslateUi(CartItemWidget)
        QtCore.QMetaObject.connectSlotsByName(CartItemWidget)

    def retranslateUi(self, CartItemWidget):
        _translate = QtCore.QCoreApplication.translate
        CartItemWidget.setWindowTitle(_translate("CartItemWidget", "Form"))
        self.label_image.setText(_translate("CartItemWidget", "상품이미지"))
        self.label_name.setText(_translate("CartItemWidget", "신선 식품 무농약 양상추"))
        self.label_price.setText(_translate("CartItemWidget", "개당 3,150원"))
        self.btn_increase.setText(_translate("CartItemWidget", "+"))
        self.edit_quantity.setText(_translate("CartItemWidget", "2"))
        self.btn_decrease.setText(_translate("CartItemWidget", "-"))
        self.label_total_price.setText(_translate("CartItemWidget", "6,300원"))
        self.btn_delete.setText(_translate("CartItemWidget", "삭제"))
