# Form implementation generated from reading ui file '/home/addinedu/dev_ws/roscamp-repo-1/shopee_ros2/src/shopee_app/shopee_app/ui/dialog_profile.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dialog_profile(object):
    def setupUi(self, dialog_profile):
        dialog_profile.setObjectName("dialog_profile")
        dialog_profile.resize(400, 300)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(dialog_profile)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_user_name = QtWidgets.QLabel(parent=dialog_profile)
        self.label_user_name.setObjectName("label_user_name")
        self.horizontalLayout.addWidget(self.label_user_name)
        self.btn_edit = QtWidgets.QToolButton(parent=dialog_profile)
        self.btn_edit.setObjectName("btn_edit")
        self.horizontalLayout.addWidget(self.btn_edit)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=dialog_profile)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.labal_gender = QtWidgets.QLabel(parent=dialog_profile)
        self.labal_gender.setObjectName("labal_gender")
        self.horizontalLayout_2.addWidget(self.labal_gender)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.label_4 = QtWidgets.QLabel(parent=dialog_profile)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_allergy_info = QtWidgets.QLabel(parent=dialog_profile)
        self.label_allergy_info.setWordWrap(True)
        self.label_allergy_info.setObjectName("label_allergy_info")
        self.verticalLayout_2.addWidget(self.label_allergy_info)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(parent=dialog_profile)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.label_is_vegan = QtWidgets.QLabel(parent=dialog_profile)
        self.label_is_vegan.setObjectName("label_is_vegan")
        self.horizontalLayout_3.addWidget(self.label_is_vegan)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_8 = QtWidgets.QLabel(parent=dialog_profile)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.btn_logout = QtWidgets.QToolButton(parent=dialog_profile)
        self.btn_logout.setObjectName("btn_logout")
        self.horizontalLayout_4.addWidget(self.btn_logout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)

        self.retranslateUi(dialog_profile)
        QtCore.QMetaObject.connectSlotsByName(dialog_profile)

    def retranslateUi(self, dialog_profile):
        _translate = QtCore.QCoreApplication.translate
        dialog_profile.setWindowTitle(_translate("dialog_profile", "Dialog"))
        self.label_user_name.setText(_translate("dialog_profile", "최 쇼피"))
        self.btn_edit.setText(_translate("dialog_profile", "수정"))
        self.label_2.setText(_translate("dialog_profile", "성별 : "))
        self.labal_gender.setText(_translate("dialog_profile", "남"))
        self.label_4.setText(_translate("dialog_profile", "알러지 정보"))
        self.label_allergy_info.setText(_translate("dialog_profile", "갑각류 / 견과류 / 알류 / 우유 / 메밀 / 땅콩 / 대두 / 밀"))
        self.label_6.setText(_translate("dialog_profile", "비건 유무 : "))
        self.label_is_vegan.setText(_translate("dialog_profile", "Yes"))
        self.label_8.setText(_translate("dialog_profile", "Logout"))
        self.btn_logout.setText(_translate("dialog_profile", "->"))
