# Form implementation generated from reading ui file 'shopee_ros2/src/main_service/main_service/dashboard/ui/tab_overview.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_OverviewTab(object):
    def setupUi(self, OverviewTab):
        OverviewTab.setObjectName("OverviewTab")
        OverviewTab.resize(1200, 800)
        OverviewTab.setMinimumSize(QtCore.QSize(1200, 800))
        self.metrics_group = QtWidgets.QGroupBox(parent=OverviewTab)
        self.metrics_group.setGeometry(QtCore.QRect(10, 10, 1180, 120))
        self.metrics_group.setObjectName("metrics_group")
        self.avg_processing_time_label = QtWidgets.QLabel(parent=self.metrics_group)
        self.avg_processing_time_label.setGeometry(QtCore.QRect(20, 40, 200, 20))
        self.avg_processing_time_label.setObjectName("avg_processing_time_label")
        self.hourly_throughput_label = QtWidgets.QLabel(parent=self.metrics_group)
        self.hourly_throughput_label.setGeometry(QtCore.QRect(20, 80, 200, 20))
        self.hourly_throughput_label.setObjectName("hourly_throughput_label")
        self.robot_utilization_label = QtWidgets.QLabel(parent=self.metrics_group)
        self.robot_utilization_label.setGeometry(QtCore.QRect(390, 40, 100, 20))
        self.robot_utilization_label.setObjectName("robot_utilization_label")
        self.robot_utilization_progress = QtWidgets.QProgressBar(parent=self.metrics_group)
        self.robot_utilization_progress.setGeometry(QtCore.QRect(500, 40, 120, 20))
        self.robot_utilization_progress.setProperty("value", 0)
        self.robot_utilization_progress.setObjectName("robot_utilization_progress")
        self.system_load_label = QtWidgets.QLabel(parent=self.metrics_group)
        self.system_load_label.setGeometry(QtCore.QRect(390, 80, 100, 20))
        self.system_load_label.setObjectName("system_load_label")
        self.system_load_progress = QtWidgets.QProgressBar(parent=self.metrics_group)
        self.system_load_progress.setGeometry(QtCore.QRect(500, 80, 120, 20))
        self.system_load_progress.setProperty("value", 0)
        self.system_load_progress.setObjectName("system_load_progress")
        self.success_rate_label = QtWidgets.QLabel(parent=self.metrics_group)
        self.success_rate_label.setGeometry(QtCore.QRect(800, 40, 80, 20))
        self.success_rate_label.setObjectName("success_rate_label")
        self.success_rate_progress = QtWidgets.QProgressBar(parent=self.metrics_group)
        self.success_rate_progress.setGeometry(QtCore.QRect(890, 40, 120, 20))
        self.success_rate_progress.setProperty("value", 0)
        self.success_rate_progress.setObjectName("success_rate_progress")
        self.active_orders_label = QtWidgets.QLabel(parent=self.metrics_group)
        self.active_orders_label.setGeometry(QtCore.QRect(800, 80, 200, 20))
        self.active_orders_label.setObjectName("active_orders_label")
        self.status_summary_group = QtWidgets.QGroupBox(parent=OverviewTab)
        self.status_summary_group.setGeometry(QtCore.QRect(10, 140, 450, 650))
        self.status_summary_group.setObjectName("status_summary_group")
        self.status_tree_widget = QtWidgets.QTreeWidget(parent=self.status_summary_group)
        self.status_tree_widget.setGeometry(QtCore.QRect(10, 25, 430, 615))
        self.status_tree_widget.setObjectName("status_tree_widget")
        self.event_log_group = QtWidgets.QGroupBox(parent=OverviewTab)
        self.event_log_group.setGeometry(QtCore.QRect(470, 140, 720, 650))
        self.event_log_group.setObjectName("event_log_group")
        self.event_table_view = QtWidgets.QTableView(parent=self.event_log_group)
        self.event_table_view.setGeometry(QtCore.QRect(10, 25, 700, 615))
        self.event_table_view.setObjectName("event_table_view")

        self.retranslateUi(OverviewTab)
        QtCore.QMetaObject.connectSlotsByName(OverviewTab)

    def retranslateUi(self, OverviewTab):
        _translate = QtCore.QCoreApplication.translate
        self.metrics_group.setTitle(_translate("OverviewTab", "시스템 성능 메트릭스"))
        self.avg_processing_time_label.setText(_translate("OverviewTab", "평균 처리 시간: 0.0초"))
        self.hourly_throughput_label.setText(_translate("OverviewTab", "시간당 처리량: 0건"))
        self.robot_utilization_label.setText(_translate("OverviewTab", "로봇 가동률:"))
        self.system_load_label.setText(_translate("OverviewTab", "시스템 부하:"))
        self.success_rate_label.setText(_translate("OverviewTab", "성공률:"))
        self.active_orders_label.setText(_translate("OverviewTab", "활성 주문: 0건"))
        self.status_summary_group.setTitle(_translate("OverviewTab", "시스템 상태 요약"))
        self.status_tree_widget.headerItem().setText(0, _translate("OverviewTab", "항목"))
        self.status_tree_widget.headerItem().setText(1, _translate("OverviewTab", "값"))
        self.event_log_group.setTitle(_translate("OverviewTab", "실시간 이벤트 로그"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OverviewTab = QtWidgets.QWidget()
    ui = Ui_OverviewTab()
    ui.setupUi(OverviewTab)
    OverviewTab.show()
    sys.exit(app.exec())
