# Form implementation generated from reading ui file 'ui/tab_ros_service_request.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RosServiceRequestTab(object):
    def setupUi(self, RosServiceRequestTab):
        RosServiceRequestTab.setObjectName("RosServiceRequestTab")
        RosServiceRequestTab.resize(1880, 1000)
        RosServiceRequestTab.setMinimumSize(QtCore.QSize(1880, 1000))
        self.horizontalLayout = QtWidgets.QHBoxLayout(RosServiceRequestTab)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.main_splitter = QtWidgets.QSplitter(parent=RosServiceRequestTab)
        self.main_splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.main_splitter.setObjectName("main_splitter")
        self.service_list_groupbox = QtWidgets.QGroupBox(parent=self.main_splitter)
        self.service_list_groupbox.setObjectName("service_list_groupbox")
        self.verticalLayout_left = QtWidgets.QVBoxLayout(self.service_list_groupbox)
        self.verticalLayout_left.setObjectName("verticalLayout_left")
        self.search_layout = QtWidgets.QHBoxLayout()
        self.search_layout.setObjectName("search_layout")
        self.search_label = QtWidgets.QLabel(parent=self.service_list_groupbox)
        self.search_label.setObjectName("search_label")
        self.search_layout.addWidget(self.search_label)
        self.search_input = QtWidgets.QLineEdit(parent=self.service_list_groupbox)
        self.search_input.setObjectName("search_input")
        self.search_layout.addWidget(self.search_input)
        self.verticalLayout_left.addLayout(self.search_layout)
        self.service_tree = QtWidgets.QTreeWidget(parent=self.service_list_groupbox)
        self.service_tree.setObjectName("service_tree")
        self.verticalLayout_left.addWidget(self.service_tree)
        self.right_widget = QtWidgets.QWidget(parent=self.main_splitter)
        self.right_widget.setObjectName("right_widget")
        self.verticalLayout_right = QtWidgets.QVBoxLayout(self.right_widget)
        self.verticalLayout_right.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_right.setObjectName("verticalLayout_right")
        self.right_splitter = QtWidgets.QSplitter(parent=self.right_widget)
        self.right_splitter.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.right_splitter.setObjectName("right_splitter")
        self.param_groupbox = QtWidgets.QGroupBox(parent=self.right_splitter)
        self.param_groupbox.setObjectName("param_groupbox")
        self.verticalLayout_param = QtWidgets.QVBoxLayout(self.param_groupbox)
        self.verticalLayout_param.setObjectName("verticalLayout_param")
        self.service_desc_label = QtWidgets.QLabel(parent=self.param_groupbox)
        self.service_desc_label.setWordWrap(True)
        self.service_desc_label.setStyleSheet("color: #666; font-style: italic;")
        self.service_desc_label.setObjectName("service_desc_label")
        self.verticalLayout_param.addWidget(self.service_desc_label)
        self.param_scroll_area = QtWidgets.QScrollArea(parent=self.param_groupbox)
        self.param_scroll_area.setWidgetResizable(True)
        self.param_scroll_area.setMinimumHeight(200)
        self.param_scroll_area.setObjectName("param_scroll_area")
        self.param_scroll_contents = QtWidgets.QWidget()
        self.param_scroll_contents.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.param_scroll_contents.setObjectName("param_scroll_contents")
        self.param_form_layout = QtWidgets.QFormLayout(self.param_scroll_contents)
        self.param_form_layout.setObjectName("param_form_layout")
        self.param_scroll_area.setWidget(self.param_scroll_contents)
        self.verticalLayout_param.addWidget(self.param_scroll_area)
        self.button_layout = QtWidgets.QHBoxLayout()
        self.button_layout.setObjectName("button_layout")
        self.reset_button = QtWidgets.QPushButton(parent=self.param_groupbox)
        self.reset_button.setEnabled(False)
        self.reset_button.setObjectName("reset_button")
        self.button_layout.addWidget(self.reset_button)
        self.call_button = QtWidgets.QPushButton(parent=self.param_groupbox)
        self.call_button.setEnabled(False)
        self.call_button.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    padding: 8px 16px;\n"
"    border-radius: 4px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #45a049;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: #cccccc;\n"
"}")
        self.call_button.setObjectName("call_button")
        self.button_layout.addWidget(self.call_button)
        self.verticalLayout_param.addLayout(self.button_layout)
        self.result_groupbox = QtWidgets.QGroupBox(parent=self.right_splitter)
        self.result_groupbox.setObjectName("result_groupbox")
        self.verticalLayout_result = QtWidgets.QVBoxLayout(self.result_groupbox)
        self.verticalLayout_result.setObjectName("verticalLayout_result")
        self.clear_button_layout = QtWidgets.QHBoxLayout()
        self.clear_button_layout.setObjectName("clear_button_layout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.clear_button_layout.addItem(spacerItem)
        self.clear_log_button = QtWidgets.QPushButton(parent=self.result_groupbox)
        self.clear_log_button.setObjectName("clear_log_button")
        self.clear_button_layout.addWidget(self.clear_log_button)
        self.verticalLayout_result.addLayout(self.clear_button_layout)
        self.result_log = QtWidgets.QTextEdit(parent=self.result_groupbox)
        self.result_log.setReadOnly(True)
        self.result_log.setMinimumHeight(150)
        self.result_log.setStyleSheet("QTextEdit {\n"
"    background-color: #1e1e1e;\n"
"    color: #d4d4d4;\n"
"    font-family: \"Courier New\", monospace;\n"
"    font-size: 11px;\n"
"}")
        self.result_log.setObjectName("result_log")
        self.verticalLayout_result.addWidget(self.result_log)
        self.verticalLayout_right.addWidget(self.right_splitter)
        self.horizontalLayout.addWidget(self.main_splitter)

        self.retranslateUi(RosServiceRequestTab)
        QtCore.QMetaObject.connectSlotsByName(RosServiceRequestTab)

    def retranslateUi(self, RosServiceRequestTab):
        _translate = QtCore.QCoreApplication.translate
        RosServiceRequestTab.setWindowTitle(_translate("RosServiceRequestTab", "Form"))
        self.service_list_groupbox.setTitle(_translate("RosServiceRequestTab", "📡 서비스 목록"))
        self.search_label.setText(_translate("RosServiceRequestTab", "검색:"))
        self.search_input.setPlaceholderText(_translate("RosServiceRequestTab", "서비스 이름 검색..."))
        self.service_tree.headerItem().setText(0, _translate("RosServiceRequestTab", "서비스"))
        self.param_groupbox.setTitle(_translate("RosServiceRequestTab", "⚙️ 서비스 파라미터"))
        self.service_desc_label.setText(_translate("RosServiceRequestTab", "← 좌측에서 서비스를 선택하세요"))
        self.reset_button.setText(_translate("RosServiceRequestTab", "🔄 초기화"))
        self.call_button.setText(_translate("RosServiceRequestTab", "📤 서비스 호출"))
        self.result_groupbox.setTitle(_translate("RosServiceRequestTab", "📋 결과 로그"))
        self.clear_log_button.setText(_translate("RosServiceRequestTab", "🗑️ 로그 지우기"))
