# Form implementation generated from reading ui file 'ui/tab_overview.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_OverviewTab(object):
    def setupUi(self, OverviewTab):
        OverviewTab.setObjectName("OverviewTab")
        OverviewTab.resize(1200, 800)
        OverviewTab.setMinimumSize(QtCore.QSize(1200, 800))
        self.metrics_group = QtWidgets.QGroupBox(parent=OverviewTab)
        self.metrics_group.setGeometry(QtCore.QRect(10, 10, 1180, 120))
        self.metrics_group.setObjectName("metrics_group")
        self.avg_processing_time_label = QtWidgets.QLabel(parent=self.metrics_group)
        self.avg_processing_time_label.setGeometry(QtCore.QRect(20, 30, 200, 20))
        self.avg_processing_time_label.setObjectName("avg_processing_time_label")
        self.hourly_throughput_label = QtWidgets.QLabel(parent=self.metrics_group)
        self.hourly_throughput_label.setGeometry(QtCore.QRect(240, 30, 200, 20))
        self.hourly_throughput_label.setObjectName("hourly_throughput_label")
        self.success_rate_label = QtWidgets.QLabel(parent=self.metrics_group)
        self.success_rate_label.setGeometry(QtCore.QRect(460, 30, 200, 20))
        self.success_rate_label.setObjectName("success_rate_label")
        self.robot_utilization_label = QtWidgets.QLabel(parent=self.metrics_group)
        self.robot_utilization_label.setGeometry(QtCore.QRect(20, 60, 200, 20))
        self.robot_utilization_label.setObjectName("robot_utilization_label")
        self.system_load_label = QtWidgets.QLabel(parent=self.metrics_group)
        self.system_load_label.setGeometry(QtCore.QRect(240, 60, 200, 20))
        self.system_load_label.setObjectName("system_load_label")
        self.active_orders_label = QtWidgets.QLabel(parent=self.metrics_group)
        self.active_orders_label.setGeometry(QtCore.QRect(460, 60, 200, 20))
        self.active_orders_label.setObjectName("active_orders_label")
        self.alerts_group = QtWidgets.QGroupBox(parent=OverviewTab)
        self.alerts_group.setGeometry(QtCore.QRect(10, 140, 1180, 650))
        self.alerts_group.setObjectName("alerts_group")
        self.alerts_text = QtWidgets.QTextEdit(parent=self.alerts_group)
        self.alerts_text.setGeometry(QtCore.QRect(10, 25, 1160, 615))
        self.alerts_text.setReadOnly(True)
        self.alerts_text.setObjectName("alerts_text")

        self.retranslateUi(OverviewTab)
        QtCore.QMetaObject.connectSlotsByName(OverviewTab)

    def retranslateUi(self, OverviewTab):
        _translate = QtCore.QCoreApplication.translate
        self.metrics_group.setTitle(_translate("OverviewTab", "시스템 성능 메트릭스"))
        self.avg_processing_time_label.setText(_translate("OverviewTab", "평균 처리 시간: 0.0초"))
        self.hourly_throughput_label.setText(_translate("OverviewTab", "시간당 처리량: 0건"))
        self.success_rate_label.setText(_translate("OverviewTab", "성공률: 0.0%"))
        self.robot_utilization_label.setText(_translate("OverviewTab", "로봇 가동률: 0.0%"))
        self.system_load_label.setText(_translate("OverviewTab", "시스템 부하: 0.0%"))
        self.active_orders_label.setText(_translate("OverviewTab", "활성 주문: 0건"))
        self.alerts_group.setTitle(_translate("OverviewTab", "실시간 알림 및 이벤트"))
