# Form implementation generated from reading ui file 'shopee_ros2/src/main_service/main_service/dashboard/ui/tab_db_admin.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DBAdminTab(object):
    def setupUi(self, DBAdminTab):
        DBAdminTab.setObjectName("DBAdminTab")
        DBAdminTab.resize(1200, 800)
        DBAdminTab.setMinimumSize(QtCore.QSize(1200, 800))
        self.query_label = QtWidgets.QLabel(parent=DBAdminTab)
        self.query_label.setGeometry(QtCore.QRect(10, 10, 80, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.query_label.setFont(font)
        self.query_label.setObjectName("query_label")
        self.query_text_edit = QtWidgets.QTextEdit(parent=DBAdminTab)
        self.query_text_edit.setGeometry(QtCore.QRect(10, 35, 1180, 100))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.query_text_edit.setFont(font)
        self.query_text_edit.setObjectName("query_text_edit")
        self.execute_button = QtWidgets.QPushButton(parent=DBAdminTab)
        self.execute_button.setGeometry(QtCore.QRect(10, 145, 120, 25))
        self.execute_button.setObjectName("execute_button")
        self.clear_button = QtWidgets.QPushButton(parent=DBAdminTab)
        self.clear_button.setGeometry(QtCore.QRect(140, 145, 60, 25))
        self.clear_button.setObjectName("clear_button")
        self.table_combo = QtWidgets.QComboBox(parent=DBAdminTab)
        self.table_combo.setGeometry(QtCore.QRect(210, 145, 120, 25))
        self.table_combo.setObjectName("table_combo")
        self.table_combo.addItem("")
        self.table_combo.addItem("")
        self.table_combo.addItem("")
        self.table_combo.addItem("")
        self.table_combo.addItem("")
        self.table_combo.addItem("")
        self.table_combo.addItem("")
        self.show_tables_button = QtWidgets.QPushButton(parent=DBAdminTab)
        self.show_tables_button.setGeometry(QtCore.QRect(340, 145, 80, 25))
        self.show_tables_button.setObjectName("show_tables_button")
        self.result_label = QtWidgets.QLabel(parent=DBAdminTab)
        self.result_label.setGeometry(QtCore.QRect(10, 180, 80, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.result_label.setFont(font)
        self.result_label.setObjectName("result_label")
        self.result_table = QtWidgets.QTableWidget(parent=DBAdminTab)
        self.result_table.setGeometry(QtCore.QRect(10, 205, 1180, 550))
        self.result_table.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.DoubleClicked)
        self.result_table.setAlternatingRowColors(True)
        self.result_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.result_table.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.CustomContextMenu)
        self.result_table.setObjectName("result_table")
        self.result_table.setColumnCount(0)
        self.result_table.setRowCount(0)
        self.status_label = QtWidgets.QLabel(parent=DBAdminTab)
        self.status_label.setGeometry(QtCore.QRect(10, 765, 200, 20))
        self.status_label.setObjectName("status_label")
        self.export_button = QtWidgets.QPushButton(parent=DBAdminTab)
        self.export_button.setGeometry(QtCore.QRect(1100, 765, 90, 25))
        self.export_button.setObjectName("export_button")

        self.retranslateUi(DBAdminTab)
        QtCore.QMetaObject.connectSlotsByName(DBAdminTab)

    def retranslateUi(self, DBAdminTab):
        _translate = QtCore.QCoreApplication.translate
        self.query_label.setText(_translate("DBAdminTab", "SQL 쿼리:"))
        self.query_text_edit.setPlaceholderText(_translate("DBAdminTab", "SELECT * FROM product LIMIT 10;"))
        self.execute_button.setText(_translate("DBAdminTab", "실행 (Ctrl+Enter)"))
        self.execute_button.setShortcut(_translate("DBAdminTab", "Ctrl+Return"))
        self.clear_button.setText(_translate("DBAdminTab", "지우기"))
        self.table_combo.setToolTip(_translate("DBAdminTab", "테이블 선택하여 빠른 조회"))
        self.table_combo.setItemText(0, _translate("DBAdminTab", "테이블 선택..."))
        self.table_combo.setItemText(1, _translate("DBAdminTab", "product"))
        self.table_combo.setItemText(2, _translate("DBAdminTab", "order"))
        self.table_combo.setItemText(3, _translate("DBAdminTab", "customer"))
        self.table_combo.setItemText(4, _translate("DBAdminTab", "order_item"))
        self.table_combo.setItemText(5, _translate("DBAdminTab", "robot"))
        self.table_combo.setItemText(6, _translate("DBAdminTab", "robot_history"))
        self.show_tables_button.setText(_translate("DBAdminTab", "테이블 목록"))
        self.result_label.setText(_translate("DBAdminTab", "쿼리 결과:"))
        self.result_table.setSortingEnabled(True)
        self.status_label.setText(_translate("DBAdminTab", "준비"))
        self.export_button.setText(_translate("DBAdminTab", "CSV 내보내기"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DBAdminTab = QtWidgets.QWidget()
    ui = Ui_DBAdminTab()
    ui.setupUi(DBAdminTab)
    DBAdminTab.show()
    sys.exit(app.exec())
