# Form implementation generated from reading ui file 'shopee_ros2/src/main_service/main_service/dashboard/ui/tab_video_monitor.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_VideoMonitorTab(object):
    def setupUi(self, VideoMonitorTab):
        VideoMonitorTab.setObjectName("VideoMonitorTab")
        VideoMonitorTab.resize(1880, 1000)
        VideoMonitorTab.setMinimumSize(QtCore.QSize(1880, 1000))
        self.label_robot = QtWidgets.QLabel(parent=VideoMonitorTab)
        self.label_robot.setGeometry(QtCore.QRect(30, 20, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_robot.setFont(font)
        self.label_robot.setObjectName("label_robot")
        self.robot_selector = QtWidgets.QComboBox(parent=VideoMonitorTab)
        self.robot_selector.setGeometry(QtCore.QRect(120, 20, 200, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.robot_selector.setFont(font)
        self.robot_selector.setObjectName("robot_selector")
        self.refresh_button = QtWidgets.QPushButton(parent=VideoMonitorTab)
        self.refresh_button.setGeometry(QtCore.QRect(340, 20, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.refresh_button.setFont(font)
        self.refresh_button.setObjectName("refresh_button")
        self.video_group = QtWidgets.QGroupBox(parent=VideoMonitorTab)
        self.video_group.setGeometry(QtCore.QRect(29, 59, 1811, 911))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.video_group.setFont(font)
        self.video_group.setStyleSheet("QGroupBox {\n"
" border: 1px solid #dcdcdc;\n"
" margin-top: 10px;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
" subcontrol-origin: margin;\n"
" subcontrol-position: top left;\n"
" left: 20px;\n"
" top: 25px;\n"
" padding: 5px 10px;\n"
" background-color: #3498db;\n"
" color: white;\n"
" border-radius: 3px;\n"
"}\n"
"    ")
        self.video_group.setObjectName("video_group")
        self.video_label = QtWidgets.QLabel(parent=self.video_group)
        self.video_label.setGeometry(QtCore.QRect(19, 64, 1771, 821))
        self.video_label.setStyleSheet("\n"
"QLabel {\n"
" background-color: black;\n"
" color: white;\n"
" font-size: 14pt;\n"
"}\n"
"     ")
        self.video_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.video_label.setObjectName("video_label")

        self.retranslateUi(VideoMonitorTab)
        QtCore.QMetaObject.connectSlotsByName(VideoMonitorTab)

    def retranslateUi(self, VideoMonitorTab):
        _translate = QtCore.QCoreApplication.translate
        self.label_robot.setText(_translate("VideoMonitorTab", "로봇 선택:"))
        self.refresh_button.setText(_translate("VideoMonitorTab", "새로고침"))
        self.video_group.setTitle(_translate("VideoMonitorTab", "🤖 로봇 선택 대기 중..."))
        self.video_label.setText(_translate("VideoMonitorTab", "로봇을 선택하세요"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VideoMonitorTab = QtWidgets.QWidget()
    ui = Ui_VideoMonitorTab()
    ui.setupUi(VideoMonitorTab)
    VideoMonitorTab.show()
    sys.exit(app.exec())
