# Form implementation generated from reading ui file 'shopee_ros2/src/main_service/main_service/dashboard/ui/tab_tcp_monitor.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TCPMonitorTab(object):
    def setupUi(self, TCPMonitorTab):
        TCPMonitorTab.setObjectName("TCPMonitorTab")
        TCPMonitorTab.resize(800, 600)
        self.gridLayout = QtWidgets.QGridLayout(TCPMonitorTab)
        self.gridLayout.setObjectName("gridLayout")
        self.tab_widget = QtWidgets.QTabWidget(parent=TCPMonitorTab)
        self.tab_widget.setObjectName("tab_widget")
        self.received_tab = QtWidgets.QWidget()
        self.received_tab.setObjectName("received_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.received_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.received_text = QtWidgets.QPlainTextEdit(parent=self.received_tab)
        self.received_text.setReadOnly(True)
        self.received_text.setObjectName("received_text")
        self.gridLayout_2.addWidget(self.received_text, 0, 0, 1, 1)
        self.tab_widget.addTab(self.received_tab, "")
        self.sent_tab = QtWidgets.QWidget()
        self.sent_tab.setObjectName("sent_tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.sent_tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.sent_text = QtWidgets.QPlainTextEdit(parent=self.sent_tab)
        self.sent_text.setReadOnly(True)
        self.sent_text.setObjectName("sent_text")
        self.gridLayout_3.addWidget(self.sent_text, 0, 0, 1, 1)
        self.tab_widget.addTab(self.sent_tab, "")
        self.gridLayout.addWidget(self.tab_widget, 0, 0, 1, 1)

        self.retranslateUi(TCPMonitorTab)
        self.tab_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TCPMonitorTab)

    def retranslateUi(self, TCPMonitorTab):
        _translate = QtCore.QCoreApplication.translate
        TCPMonitorTab.setWindowTitle(_translate("TCPMonitorTab", "Form"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.received_tab), _translate("TCPMonitorTab", "수신 (Received)"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.sent_tab), _translate("TCPMonitorTab", "송신 (Sent)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TCPMonitorTab = QtWidgets.QWidget()
    ui = Ui_TCPMonitorTab()
    ui.setupUi(TCPMonitorTab)
    TCPMonitorTab.show()
    sys.exit(app.exec())
