# Form implementation generated from reading ui file 'shopee_ros2/src/main_service/main_service/dashboard/ui/tab_tcp_tester.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TcpTesterTab(object):
    def setupUi(self, TcpTesterTab):
        TcpTesterTab.setObjectName("TcpTesterTab")
        TcpTesterTab.resize(1880, 1000)
        TcpTesterTab.setMinimumSize(QtCore.QSize(1880, 1000))
        self.horizontalLayout = QtWidgets.QHBoxLayout(TcpTesterTab)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.main_splitter = QtWidgets.QSplitter(parent=TcpTesterTab)
        self.main_splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.main_splitter.setObjectName("main_splitter")
        self.message_list_groupbox = QtWidgets.QGroupBox(parent=self.main_splitter)
        self.message_list_groupbox.setMinimumSize(QtCore.QSize(300, 0))
        self.message_list_groupbox.setObjectName("message_list_groupbox")
        self.verticalLayout_left = QtWidgets.QVBoxLayout(self.message_list_groupbox)
        self.verticalLayout_left.setObjectName("verticalLayout_left")
        self.message_tree = QtWidgets.QTreeWidget(parent=self.message_list_groupbox)
        self.message_tree.setObjectName("message_tree")
        self.verticalLayout_left.addWidget(self.message_tree)
        self.right_widget = QtWidgets.QWidget(parent=self.main_splitter)
        self.right_widget.setObjectName("right_widget")
        self.verticalLayout_right = QtWidgets.QVBoxLayout(self.right_widget)
        self.verticalLayout_right.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_right.setObjectName("verticalLayout_right")
        self.right_splitter = QtWidgets.QSplitter(parent=self.right_widget)
        self.right_splitter.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.right_splitter.setObjectName("right_splitter")
        self.connection_groupbox = QtWidgets.QGroupBox(parent=self.right_splitter)
        self.connection_groupbox.setObjectName("connection_groupbox")
        self.verticalLayout_connection = QtWidgets.QVBoxLayout(self.connection_groupbox)
        self.verticalLayout_connection.setObjectName("verticalLayout_connection")
        self.connection_layout = QtWidgets.QHBoxLayout()
        self.connection_layout.setObjectName("connection_layout")
        self.host_label = QtWidgets.QLabel(parent=self.connection_groupbox)
        self.host_label.setObjectName("host_label")
        self.connection_layout.addWidget(self.host_label)
        self.host_input = QtWidgets.QLineEdit(parent=self.connection_groupbox)
        self.host_input.setObjectName("host_input")
        self.connection_layout.addWidget(self.host_input)
        self.port_label = QtWidgets.QLabel(parent=self.connection_groupbox)
        self.port_label.setObjectName("port_label")
        self.connection_layout.addWidget(self.port_label)
        self.port_input = QtWidgets.QLineEdit(parent=self.connection_groupbox)
        self.port_input.setMaximumWidth(100)
        self.port_input.setObjectName("port_input")
        self.connection_layout.addWidget(self.port_input)
        self.connect_button = QtWidgets.QPushButton(parent=self.connection_groupbox)
        self.connect_button.setObjectName("connect_button")
        self.connection_layout.addWidget(self.connect_button)
        self.disconnect_button = QtWidgets.QPushButton(parent=self.connection_groupbox)
        self.disconnect_button.setEnabled(False)
        self.disconnect_button.setObjectName("disconnect_button")
        self.connection_layout.addWidget(self.disconnect_button)
        self.connection_status_label = QtWidgets.QLabel(parent=self.connection_groupbox)
        self.connection_status_label.setObjectName("connection_status_label")
        self.connection_layout.addWidget(self.connection_status_label)
        self.verticalLayout_connection.addLayout(self.connection_layout)
        self.message_fields_groupbox = QtWidgets.QGroupBox(parent=self.right_splitter)
        self.message_fields_groupbox.setObjectName("message_fields_groupbox")
        self.verticalLayout_fields = QtWidgets.QVBoxLayout(self.message_fields_groupbox)
        self.verticalLayout_fields.setObjectName("verticalLayout_fields")
        self.message_desc_label = QtWidgets.QLabel(parent=self.message_fields_groupbox)
        self.message_desc_label.setWordWrap(True)
        self.message_desc_label.setStyleSheet("color: #666; font-style: italic;")
        self.message_desc_label.setObjectName("message_desc_label")
        self.verticalLayout_fields.addWidget(self.message_desc_label)
        self.fields_scroll_area = QtWidgets.QScrollArea(parent=self.message_fields_groupbox)
        self.fields_scroll_area.setWidgetResizable(True)
        self.fields_scroll_area.setMinimumHeight(200)
        self.fields_scroll_area.setObjectName("fields_scroll_area")
        self.fields_scroll_contents = QtWidgets.QWidget()
        self.fields_scroll_contents.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.fields_scroll_contents.setObjectName("fields_scroll_contents")
        self.fields_form_layout = QtWidgets.QFormLayout(self.fields_scroll_contents)
        self.fields_form_layout.setObjectName("fields_form_layout")
        self.fields_scroll_area.setWidget(self.fields_scroll_contents)
        self.verticalLayout_fields.addWidget(self.fields_scroll_area)
        self.button_layout = QtWidgets.QHBoxLayout()
        self.button_layout.setObjectName("button_layout")
        self.reset_button = QtWidgets.QPushButton(parent=self.message_fields_groupbox)
        self.reset_button.setEnabled(False)
        self.reset_button.setObjectName("reset_button")
        self.button_layout.addWidget(self.reset_button)
        self.send_button = QtWidgets.QPushButton(parent=self.message_fields_groupbox)
        self.send_button.setEnabled(False)
        self.send_button.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    padding: 8px 16px;\n"
"    border-radius: 4px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #45a049;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: #cccccc;\n"
"}")
        self.send_button.setObjectName("send_button")
        self.button_layout.addWidget(self.send_button)
        self.verticalLayout_fields.addLayout(self.button_layout)
        self.log_groupbox = QtWidgets.QGroupBox(parent=self.right_splitter)
        self.log_groupbox.setObjectName("log_groupbox")
        self.verticalLayout_log = QtWidgets.QVBoxLayout(self.log_groupbox)
        self.verticalLayout_log.setObjectName("verticalLayout_log")
        self.clear_button_layout = QtWidgets.QHBoxLayout()
        self.clear_button_layout.setObjectName("clear_button_layout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.clear_button_layout.addItem(spacerItem)
        self.clear_log_button = QtWidgets.QPushButton(parent=self.log_groupbox)
        self.clear_log_button.setObjectName("clear_log_button")
        self.clear_button_layout.addWidget(self.clear_log_button)
        self.verticalLayout_log.addLayout(self.clear_button_layout)
        self.result_log = QtWidgets.QTextEdit(parent=self.log_groupbox)
        self.result_log.setReadOnly(True)
        self.result_log.setMinimumHeight(150)
        self.result_log.setStyleSheet("QTextEdit {\n"
"    background-color: #1e1e1e;\n"
"    color: #d4d4d4;\n"
"    font-family: \"Courier New\", monospace;\n"
"    font-size: 11px;\n"
"}")
        self.result_log.setObjectName("result_log")
        self.verticalLayout_log.addWidget(self.result_log)
        self.verticalLayout_right.addWidget(self.right_splitter)
        self.horizontalLayout.addWidget(self.main_splitter)

        self.retranslateUi(TcpTesterTab)
        QtCore.QMetaObject.connectSlotsByName(TcpTesterTab)

    def retranslateUi(self, TcpTesterTab):
        _translate = QtCore.QCoreApplication.translate
        TcpTesterTab.setWindowTitle(_translate("TcpTesterTab", "Form"))
        self.message_list_groupbox.setTitle(_translate("TcpTesterTab", "📡 TCP 메시지 목록"))
        self.message_tree.headerItem().setText(0, _translate("TcpTesterTab", "메시지 타입"))
        self.connection_groupbox.setTitle(_translate("TcpTesterTab", "🔌 TCP 연결"))
        self.host_label.setText(_translate("TcpTesterTab", "호스트:"))
        self.host_input.setText(_translate("TcpTesterTab", "localhost"))
        self.port_label.setText(_translate("TcpTesterTab", "포트:"))
        self.port_input.setText(_translate("TcpTesterTab", "5000"))
        self.connect_button.setText(_translate("TcpTesterTab", "🔗 연결"))
        self.disconnect_button.setText(_translate("TcpTesterTab", "🔌 연결 해제"))
        self.connection_status_label.setText(_translate("TcpTesterTab", "⚪ 연결 안됨"))
        self.message_fields_groupbox.setTitle(_translate("TcpTesterTab", "📝 메시지 필드"))
        self.message_desc_label.setText(_translate("TcpTesterTab", "← 좌측에서 메시지 타입을 선택하세요"))
        self.reset_button.setText(_translate("TcpTesterTab", "🔄 초기화"))
        self.send_button.setText(_translate("TcpTesterTab", "📤 메시지 전송"))
        self.log_groupbox.setTitle(_translate("TcpTesterTab", "📋 통신 로그"))
        self.clear_log_button.setText(_translate("TcpTesterTab", "🗑️ 로그 지우기"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TcpTesterTab = QtWidgets.QWidget()
    ui = Ui_TcpTesterTab()
    ui.setupUi(TcpTesterTab)
    TcpTesterTab.show()
    sys.exit(app.exec())
