# Form implementation generated from reading ui file 'shopee_ros2/src/main_service/main_service/dashboard/ui/tab_robot_status.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RobotStatusTab(object):
    def setupUi(self, RobotStatusTab):
        RobotStatusTab.setObjectName("RobotStatusTab")
        RobotStatusTab.resize(1200, 800)
        RobotStatusTab.setMinimumSize(QtCore.QSize(1200, 800))
        self.robot_table = QtWidgets.QTableWidget(parent=RobotStatusTab)
        self.robot_table.setGeometry(QtCore.QRect(10, 10, 1180, 780))
        self.robot_table.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.robot_table.setAlternatingRowColors(True)
        self.robot_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.robot_table.setObjectName("robot_table")
        self.robot_table.setColumnCount(11)
        self.robot_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.robot_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.robot_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.robot_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.robot_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.robot_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.robot_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.robot_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.robot_table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.robot_table.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.robot_table.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.robot_table.setHorizontalHeaderItem(10, item)

        self.retranslateUi(RobotStatusTab)
        QtCore.QMetaObject.connectSlotsByName(RobotStatusTab)

    def retranslateUi(self, RobotStatusTab):
        _translate = QtCore.QCoreApplication.translate
        item = self.robot_table.horizontalHeaderItem(0)
        item.setText(_translate("RobotStatusTab", "Robot ID"))
        item = self.robot_table.horizontalHeaderItem(1)
        item.setText(_translate("RobotStatusTab", "Type"))
        item = self.robot_table.horizontalHeaderItem(2)
        item.setText(_translate("RobotStatusTab", "Status"))
        item = self.robot_table.horizontalHeaderItem(3)
        item.setText(_translate("RobotStatusTab", "Detailed Status"))
        item = self.robot_table.horizontalHeaderItem(4)
        item.setText(_translate("RobotStatusTab", "Battery(%)"))
        item = self.robot_table.horizontalHeaderItem(5)
        item.setText(_translate("RobotStatusTab", "Location"))
        item = self.robot_table.horizontalHeaderItem(6)
        item.setText(_translate("RobotStatusTab", "Cart"))
        item = self.robot_table.horizontalHeaderItem(7)
        item.setText(_translate("RobotStatusTab", "Reserved"))
        item = self.robot_table.horizontalHeaderItem(8)
        item.setText(_translate("RobotStatusTab", "Order ID"))
        item = self.robot_table.horizontalHeaderItem(9)
        item.setText(_translate("RobotStatusTab", "Offline Time"))
        item = self.robot_table.horizontalHeaderItem(10)
        item.setText(_translate("RobotStatusTab", "Last Update"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RobotStatusTab = QtWidgets.QWidget()
    ui = Ui_RobotStatusTab()
    ui.setupUi(RobotStatusTab)
    RobotStatusTab.show()
    sys.exit(app.exec())
