# Form implementation generated from reading ui file 'shopee_ros2/src/main_service/main_service/dashboard/ui/tab_event_log.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EventLogTab(object):
    def setupUi(self, EventLogTab):
        EventLogTab.setObjectName("EventLogTab")
        EventLogTab.resize(1880, 1000)
        EventLogTab.setMinimumSize(QtCore.QSize(1880, 1000))
        self.filter_widget = QtWidgets.QWidget(parent=EventLogTab)
        self.filter_widget.setGeometry(QtCore.QRect(10, 10, 1180, 40))
        self.filter_widget.setObjectName("filter_widget")
        self.search_label = QtWidgets.QLabel(parent=self.filter_widget)
        self.search_label.setGeometry(QtCore.QRect(10, 10, 50, 20))
        self.search_label.setObjectName("search_label")
        self.search_line_edit = QtWidgets.QLineEdit(parent=self.filter_widget)
        self.search_line_edit.setGeometry(QtCore.QRect(70, 10, 200, 20))
        self.search_line_edit.setObjectName("search_line_edit")
        self.filter_label = QtWidgets.QLabel(parent=self.filter_widget)
        self.filter_label.setGeometry(QtCore.QRect(290, 10, 50, 20))
        self.filter_label.setObjectName("filter_label")
        self.level_filter_combo = QtWidgets.QComboBox(parent=self.filter_widget)
        self.level_filter_combo.setGeometry(QtCore.QRect(350, 10, 80, 20))
        self.level_filter_combo.setObjectName("level_filter_combo")
        self.level_filter_combo.addItem("")
        self.level_filter_combo.addItem("")
        self.level_filter_combo.addItem("")
        self.level_filter_combo.addItem("")
        self.clear_button = QtWidgets.QPushButton(parent=self.filter_widget)
        self.clear_button.setGeometry(QtCore.QRect(450, 10, 60, 20))
        self.clear_button.setObjectName("clear_button")
        self.export_button = QtWidgets.QPushButton(parent=self.filter_widget)
        self.export_button.setGeometry(QtCore.QRect(520, 10, 80, 20))
        self.export_button.setObjectName("export_button")
        self.log_table = QtWidgets.QTableWidget(parent=EventLogTab)
        self.log_table.setGeometry(QtCore.QRect(10, 60, 1180, 700))
        self.log_table.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.log_table.setAlternatingRowColors(True)
        self.log_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.log_table.setObjectName("log_table")
        self.log_table.setColumnCount(4)
        self.log_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.log_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.log_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.log_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.log_table.setHorizontalHeaderItem(3, item)
        self.status_label = QtWidgets.QLabel(parent=EventLogTab)
        self.status_label.setGeometry(QtCore.QRect(10, 770, 200, 20))
        self.status_label.setObjectName("status_label")

        self.retranslateUi(EventLogTab)
        QtCore.QMetaObject.connectSlotsByName(EventLogTab)

    def retranslateUi(self, EventLogTab):
        _translate = QtCore.QCoreApplication.translate
        self.search_label.setText(_translate("EventLogTab", "검색:"))
        self.search_line_edit.setPlaceholderText(_translate("EventLogTab", "키워드, Order ID, Robot ID 검색..."))
        self.filter_label.setText(_translate("EventLogTab", "필터:"))
        self.level_filter_combo.setItemText(0, _translate("EventLogTab", "전체"))
        self.level_filter_combo.setItemText(1, _translate("EventLogTab", "INFO"))
        self.level_filter_combo.setItemText(2, _translate("EventLogTab", "WARN"))
        self.level_filter_combo.setItemText(3, _translate("EventLogTab", "ERROR"))
        self.clear_button.setText(_translate("EventLogTab", "지우기"))
        self.export_button.setText(_translate("EventLogTab", "CSV 내보내기"))
        item = self.log_table.horizontalHeaderItem(0)
        item.setText(_translate("EventLogTab", "Time"))
        item = self.log_table.horizontalHeaderItem(1)
        item.setText(_translate("EventLogTab", "Level"))
        item = self.log_table.horizontalHeaderItem(2)
        item.setText(_translate("EventLogTab", "Type"))
        item = self.log_table.horizontalHeaderItem(3)
        item.setText(_translate("EventLogTab", "Message"))
        self.status_label.setText(_translate("EventLogTab", "총 0건 표시 중"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EventLogTab = QtWidgets.QWidget()
    ui = Ui_EventLogTab()
    ui.setupUi(EventLogTab)
    EventLogTab.show()
    sys.exit(app.exec())
