# Form implementation generated from reading ui file 'shopee_ros2/src/main_service/main_service/dashboard/ui/tab_order_management.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_OrderManagementTab(object):
    def setupUi(self, OrderManagementTab):
        OrderManagementTab.setObjectName("OrderManagementTab")
        OrderManagementTab.resize(1880, 1000)
        OrderManagementTab.setMinimumSize(QtCore.QSize(1880, 1000))
        self.order_table = QtWidgets.QTableWidget(parent=OrderManagementTab)
        self.order_table.setGeometry(QtCore.QRect(10, 10, 1851, 971))
        self.order_table.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.order_table.setAlternatingRowColors(True)
        self.order_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.order_table.setObjectName("order_table")
        self.order_table.setColumnCount(10)
        self.order_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.order_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.order_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.order_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.order_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.order_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.order_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.order_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.order_table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.order_table.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.order_table.setHorizontalHeaderItem(9, item)

        self.retranslateUi(OrderManagementTab)
        QtCore.QMetaObject.connectSlotsByName(OrderManagementTab)

    def retranslateUi(self, OrderManagementTab):
        _translate = QtCore.QCoreApplication.translate
        item = self.order_table.horizontalHeaderItem(0)
        item.setText(_translate("OrderManagementTab", "Order ID"))
        item = self.order_table.horizontalHeaderItem(1)
        item.setText(_translate("OrderManagementTab", "Customer"))
        item = self.order_table.horizontalHeaderItem(2)
        item.setText(_translate("OrderManagementTab", "Status"))
        item = self.order_table.horizontalHeaderItem(3)
        item.setText(_translate("OrderManagementTab", "Items"))
        item = self.order_table.horizontalHeaderItem(4)
        item.setText(_translate("OrderManagementTab", "Amount"))
        item = self.order_table.horizontalHeaderItem(5)
        item.setText(_translate("OrderManagementTab", "Progress(%)"))
        item = self.order_table.horizontalHeaderItem(6)
        item.setText(_translate("OrderManagementTab", "Started"))
        item = self.order_table.horizontalHeaderItem(7)
        item.setText(_translate("OrderManagementTab", "Elapsed"))
        item = self.order_table.horizontalHeaderItem(8)
        item.setText(_translate("OrderManagementTab", "Pickee"))
        item = self.order_table.horizontalHeaderItem(9)
        item.setText(_translate("OrderManagementTab", "Packee"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OrderManagementTab = QtWidgets.QWidget()
    ui = Ui_OrderManagementTab()
    ui.setupUi(OrderManagementTab)
    OrderManagementTab.show()
    sys.exit(app.exec())
