# Form implementation generated from reading ui file 'ui/tab_ros_topic_publish.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RosTopicPublishTab(object):
    def setupUi(self, RosTopicPublishTab):
        RosTopicPublishTab.setObjectName("RosTopicPublishTab")
        RosTopicPublishTab.resize(1880, 1000)
        RosTopicPublishTab.setMinimumSize(QtCore.QSize(1880, 1000))
        self.horizontalLayout = QtWidgets.QHBoxLayout(RosTopicPublishTab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(parent=RosTopicPublishTab)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setObjectName("splitter")
        self.topic_list_groupbox = QtWidgets.QGroupBox(parent=self.splitter)
        self.topic_list_groupbox.setObjectName("topic_list_groupbox")
        self.verticalLayout_1 = QtWidgets.QVBoxLayout(self.topic_list_groupbox)
        self.verticalLayout_1.setObjectName("verticalLayout_1")
        self.topic_tree = QtWidgets.QTreeWidget(parent=self.topic_list_groupbox)
        self.topic_tree.setObjectName("topic_tree")
        self.verticalLayout_1.addWidget(self.topic_tree)
        self.layoutWidget = QtWidgets.QWidget(parent=self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.right_splitter = QtWidgets.QSplitter(parent=self.layoutWidget)
        self.right_splitter.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.right_splitter.setObjectName("right_splitter")
        self.message_fields_groupbox = QtWidgets.QGroupBox(parent=self.right_splitter)
        self.message_fields_groupbox.setObjectName("message_fields_groupbox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.message_fields_groupbox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.topic_desc_label = QtWidgets.QLabel(parent=self.message_fields_groupbox)
        self.topic_desc_label.setWordWrap(True)
        self.topic_desc_label.setObjectName("topic_desc_label")
        self.verticalLayout_2.addWidget(self.topic_desc_label)
        self.scrollArea = QtWidgets.QScrollArea(parent=self.message_fields_groupbox)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.param_form_layout = QtWidgets.QFormLayout(self.scrollAreaWidgetContents)
        self.param_form_layout.setObjectName("param_form_layout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.publish_button = QtWidgets.QPushButton(parent=self.message_fields_groupbox)
        self.publish_button.setEnabled(False)
        self.publish_button.setObjectName("publish_button")
        self.verticalLayout_2.addWidget(self.publish_button)
        self.log_groupbox = QtWidgets.QGroupBox(parent=self.right_splitter)
        self.log_groupbox.setObjectName("log_groupbox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.log_groupbox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.result_log = QtWidgets.QTextEdit(parent=self.log_groupbox)
        self.result_log.setReadOnly(True)
        self.result_log.setObjectName("result_log")
        self.verticalLayout_4.addWidget(self.result_log)
        self.verticalLayout_3.addWidget(self.right_splitter)
        self.horizontalLayout.addWidget(self.splitter)

        self.retranslateUi(RosTopicPublishTab)
        QtCore.QMetaObject.connectSlotsByName(RosTopicPublishTab)

    def retranslateUi(self, RosTopicPublishTab):
        _translate = QtCore.QCoreApplication.translate
        RosTopicPublishTab.setWindowTitle(_translate("RosTopicPublishTab", "Form"))
        self.topic_list_groupbox.setTitle(_translate("RosTopicPublishTab", "📡 시뮬레이션 토픽 목록"))
        self.topic_tree.headerItem().setText(0, _translate("RosTopicPublishTab", "토픽"))
        self.message_fields_groupbox.setTitle(_translate("RosTopicPublishTab", "📝 메시지 필드"))
        self.topic_desc_label.setText(_translate("RosTopicPublishTab", "← 좌측에서 시뮬레이션할 토픽을 선택하세요 (로봇→Main 방향 테스트용)"))
        self.publish_button.setText(_translate("RosTopicPublishTab", "📤 토픽 발행 (시뮬레이션)"))
        self.log_groupbox.setTitle(_translate("RosTopicPublishTab", "📋 시뮬레이션 로그"))
