# Form implementation generated from reading ui file '/home/addinedu/dev/roscamp-repo-1/shopee_ros2/src/shopee_app/ui/cart_item.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CartItemWidget(object):
    def setupUi(self, CartItemWidget):
        CartItemWidget.setObjectName("CartItemWidget")
        CartItemWidget.resize(887, 254)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(CartItemWidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox = QtWidgets.QCheckBox(parent=CartItemWidget)
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_2.addWidget(self.checkBox)
        self.label = QtWidgets.QLabel(parent=CartItemWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=CartItemWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=CartItemWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toolButton = QtWidgets.QToolButton(parent=CartItemWidget)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout.addWidget(self.toolButton)
        self.lineEdit = QtWidgets.QLineEdit(parent=CartItemWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.toolButton_2 = QtWidgets.QToolButton(parent=CartItemWidget)
        self.toolButton_2.setObjectName("toolButton_2")
        self.horizontalLayout.addWidget(self.toolButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_4 = QtWidgets.QLabel(parent=CartItemWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.verticalLayout.setStretch(0, 3)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 3)
        self.verticalLayout.setStretch(3, 3)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.toolButton_3 = QtWidgets.QToolButton(parent=CartItemWidget)
        self.toolButton_3.setObjectName("toolButton_3")
        self.horizontalLayout_2.addWidget(self.toolButton_3)

        self.retranslateUi(CartItemWidget)
        QtCore.QMetaObject.connectSlotsByName(CartItemWidget)

    def retranslateUi(self, CartItemWidget):
        _translate = QtCore.QCoreApplication.translate
        CartItemWidget.setWindowTitle(_translate("CartItemWidget", "Form"))
        self.label.setText(_translate("CartItemWidget", "상품이미지"))
        self.label_2.setText(_translate("CartItemWidget", "신선 식품 무농약 양상추"))
        self.label_3.setText(_translate("CartItemWidget", "개당 3,150원"))
        self.toolButton.setText(_translate("CartItemWidget", "+"))
        self.lineEdit.setText(_translate("CartItemWidget", "2"))
        self.toolButton_2.setText(_translate("CartItemWidget", "-"))
        self.label_4.setText(_translate("CartItemWidget", "6,300원"))
        self.toolButton_3.setText(_translate("CartItemWidget", "삭제"))
