# Form implementation generated from reading ui file '/home/addinedu/dev_ws/Shopee/shopee_ros2/src/shopee_main_service/shopee_main_service/dashboard/ui/tab_overview.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_OverviewTab(object):
    def setupUi(self, OverviewTab):
        OverviewTab.setObjectName("OverviewTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(OverviewTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.metrics_group = QtWidgets.QGroupBox(parent=OverviewTab)
        self.metrics_group.setObjectName("metrics_group")
        self.gridLayout = QtWidgets.QGridLayout(self.metrics_group)
        self.gridLayout.setObjectName("gridLayout")
        self.avg_time_label = QtWidgets.QLabel(parent=self.metrics_group)
        self.avg_time_label.setObjectName("avg_time_label")
        self.gridLayout.addWidget(self.avg_time_label, 0, 0, 1, 1)
        self.throughput_label = QtWidgets.QLabel(parent=self.metrics_group)
        self.throughput_label.setObjectName("throughput_label")
        self.gridLayout.addWidget(self.throughput_label, 0, 1, 1, 1)
        self.success_rate_label = QtWidgets.QLabel(parent=self.metrics_group)
        self.success_rate_label.setObjectName("success_rate_label")
        self.gridLayout.addWidget(self.success_rate_label, 0, 2, 1, 1)
        self.robot_util_label = QtWidgets.QLabel(parent=self.metrics_group)
        self.robot_util_label.setObjectName("robot_util_label")
        self.gridLayout.addWidget(self.robot_util_label, 1, 0, 1, 1)
        self.system_load_label = QtWidgets.QLabel(parent=self.metrics_group)
        self.system_load_label.setObjectName("system_load_label")
        self.gridLayout.addWidget(self.system_load_label, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.metrics_group)
        self.bottom_splitter = QtWidgets.QSplitter(parent=OverviewTab)
        self.bottom_splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.bottom_splitter.setObjectName("bottom_splitter")
        self.robot_summary_group = QtWidgets.QGroupBox(parent=self.bottom_splitter)
        self.robot_summary_group.setObjectName("robot_summary_group")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.robot_summary_group)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.robot_summary_label = QtWidgets.QLabel(parent=self.robot_summary_group)
        self.robot_summary_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.robot_summary_label.setObjectName("robot_summary_label")
        self.verticalLayout_3.addWidget(self.robot_summary_label)
        self.order_summary_group = QtWidgets.QGroupBox(parent=self.bottom_splitter)
        self.order_summary_group.setObjectName("order_summary_group")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.order_summary_group)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.order_summary_label = QtWidgets.QLabel(parent=self.order_summary_group)
        self.order_summary_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.order_summary_label.setObjectName("order_summary_label")
        self.verticalLayout_4.addWidget(self.order_summary_label)
        self.verticalLayout_2.addWidget(self.bottom_splitter)
        self.alerts_group = QtWidgets.QGroupBox(parent=OverviewTab)
        self.alerts_group.setObjectName("alerts_group")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.alerts_group)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.alerts_label = QtWidgets.QLabel(parent=self.alerts_group)
        self.alerts_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.alerts_label.setObjectName("alerts_label")
        self.verticalLayout_5.addWidget(self.alerts_label)
        self.verticalLayout_2.addWidget(self.alerts_group)

        self.retranslateUi(OverviewTab)
        QtCore.QMetaObject.connectSlotsByName(OverviewTab)

    def retranslateUi(self, OverviewTab):
        _translate = QtCore.QCoreApplication.translate
        self.metrics_group.setTitle(_translate("OverviewTab", "시스템 성능 메트릭스"))
        self.avg_time_label.setText(_translate("OverviewTab", "평균 처리 시간: -"))
        self.throughput_label.setText(_translate("OverviewTab", "시간당 처리량: -"))
        self.success_rate_label.setText(_translate("OverviewTab", "성공률: -"))
        self.robot_util_label.setText(_translate("OverviewTab", "로봇 활용률: -"))
        self.system_load_label.setText(_translate("OverviewTab", "시스템 부하: -"))
        self.robot_summary_group.setTitle(_translate("OverviewTab", "활성 로봇 요약"))
        self.robot_summary_label.setText(_translate("OverviewTab", "로딩 중..."))
        self.order_summary_group.setTitle(_translate("OverviewTab", "진행 중 주문 요약"))
        self.order_summary_label.setText(_translate("OverviewTab", "로딩 중..."))
        self.alerts_group.setTitle(_translate("OverviewTab", "최근 알림 (최신 5건)"))
        self.alerts_label.setText(_translate("OverviewTab", "알림 없음"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OverviewTab = QtWidgets.QWidget()
    ui = Ui_OverviewTab()
    ui.setupUi(OverviewTab)
    OverviewTab.show()
    sys.exit(app.exec())
