# Form implementation generated from reading ui file '/home/addinedu/dev_ws/Shopee/shopee_ros2/src/shopee_main_service/shopee_main_service/dashboard/ui/tab_topic_monitor.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TopicMonitorTab(object):
    def setupUi(self, TopicMonitorTab):
        TopicMonitorTab.setObjectName("TopicMonitorTab")
        TopicMonitorTab.resize(1376, 824)
        self.verticalLayout = QtWidgets.QVBoxLayout(TopicMonitorTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(parent=TopicMonitorTab)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setObjectName("splitter")
        self.periodic_group = QtWidgets.QGroupBox(parent=self.splitter)
        self.periodic_group.setObjectName("periodic_group")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.periodic_group)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.periodic_log = QtWidgets.QTextEdit(parent=self.periodic_group)
        self.periodic_log.setReadOnly(True)
        self.periodic_log.setObjectName("periodic_log")
        self.verticalLayout_2.addWidget(self.periodic_log)
        self.event_group = QtWidgets.QGroupBox(parent=self.splitter)
        self.event_group.setObjectName("event_group")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.event_group)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.event_log = QtWidgets.QTextEdit(parent=self.event_group)
        self.event_log.setReadOnly(True)
        self.event_log.setObjectName("event_log")
        self.verticalLayout_3.addWidget(self.event_log)
        self.verticalLayout.addWidget(self.splitter)

        self.retranslateUi(TopicMonitorTab)
        QtCore.QMetaObject.connectSlotsByName(TopicMonitorTab)

    def retranslateUi(self, TopicMonitorTab):
        _translate = QtCore.QCoreApplication.translate
        TopicMonitorTab.setWindowTitle(_translate("TopicMonitorTab", "Form"))
        self.periodic_group.setTitle(_translate("TopicMonitorTab", "주기적 토픽 (Periodic Topics)"))
        self.event_group.setTitle(_translate("TopicMonitorTab", "이벤트성 토픽 (Event Topics)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TopicMonitorTab = QtWidgets.QWidget()
    ui = Ui_TopicMonitorTab()
    ui.setupUi(TopicMonitorTab)
    TopicMonitorTab.show()
    sys.exit(app.exec())
