# Form implementation generated from reading ui file '/home/addinedu/dev_ws/Shopee/shopee_ros2/src/shopee_main_service/shopee_main_service/dashboard/ui/tab_diagnostics.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SystemDiagnosticsTab(object):
    def setupUi(self, SystemDiagnosticsTab):
        SystemDiagnosticsTab.setObjectName("SystemDiagnosticsTab")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(SystemDiagnosticsTab)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.error_group = QtWidgets.QGroupBox(parent=SystemDiagnosticsTab)
        self.error_group.setObjectName("error_group")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.error_group)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.error_label = QtWidgets.QLabel(parent=self.error_group)
        self.error_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.error_label.setObjectName("error_label")
        self.verticalLayout_9.addWidget(self.error_label)
        self.verticalLayout_8.addWidget(self.error_group)
        self.network_group = QtWidgets.QGroupBox(parent=SystemDiagnosticsTab)
        self.network_group.setObjectName("network_group")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.network_group)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.network_label = QtWidgets.QLabel(parent=self.network_group)
        self.network_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.network_label.setObjectName("network_label")
        self.verticalLayout_10.addWidget(self.network_label)
        self.verticalLayout_8.addWidget(self.network_group)

        self.retranslateUi(SystemDiagnosticsTab)
        QtCore.QMetaObject.connectSlotsByName(SystemDiagnosticsTab)

    def retranslateUi(self, SystemDiagnosticsTab):
        _translate = QtCore.QCoreApplication.translate
        self.error_group.setTitle(_translate("SystemDiagnosticsTab", "에러 및 장애 추적"))
        self.error_label.setText(_translate("SystemDiagnosticsTab", "로딩 중..."))
        self.network_group.setTitle(_translate("SystemDiagnosticsTab", "네트워크 및 연결 상태"))
        self.network_label.setText(_translate("SystemDiagnosticsTab", "로딩 중..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SystemDiagnosticsTab = QtWidgets.QWidget()
    ui = Ui_SystemDiagnosticsTab()
    ui.setupUi(SystemDiagnosticsTab)
    SystemDiagnosticsTab.show()
    sys.exit(app.exec())
