# Form implementation generated from reading ui file '/home/addinedu/dev_ws/Shopee/shopee_ros2/src/shopee_main_service/shopee_main_service/dashboard/ui/tab_service_monitor.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ServiceMonitorTab(object):
    def setupUi(self, ServiceMonitorTab):
        ServiceMonitorTab.setObjectName("ServiceMonitorTab")
        ServiceMonitorTab.resize(1376, 824)
        self.verticalLayout = QtWidgets.QVBoxLayout(ServiceMonitorTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.service_table = QtWidgets.QTableWidget(parent=ServiceMonitorTab)
        self.service_table.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.service_table.setAlternatingRowColors(True)
        self.service_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.service_table.setObjectName("service_table")
        self.service_table.setColumnCount(7)
        self.service_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.service_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.service_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.service_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.service_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.service_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.service_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.service_table.setHorizontalHeaderItem(6, item)
        self.verticalLayout.addWidget(self.service_table)

        self.retranslateUi(ServiceMonitorTab)
        QtCore.QMetaObject.connectSlotsByName(ServiceMonitorTab)

    def retranslateUi(self, ServiceMonitorTab):
        _translate = QtCore.QCoreApplication.translate
        ServiceMonitorTab.setWindowTitle(_translate("ServiceMonitorTab", "Form"))
        item = self.service_table.horizontalHeaderItem(0)
        item.setText(_translate("ServiceMonitorTab", "Time"))
        item = self.service_table.horizontalHeaderItem(1)
        item.setText(_translate("ServiceMonitorTab", "Service Name"))
        item = self.service_table.horizontalHeaderItem(2)
        item.setText(_translate("ServiceMonitorTab", "Direction"))
        item = self.service_table.horizontalHeaderItem(3)
        item.setText(_translate("ServiceMonitorTab", "Status"))
        item = self.service_table.horizontalHeaderItem(4)
        item.setText(_translate("ServiceMonitorTab", "Duration (ms)"))
        item = self.service_table.horizontalHeaderItem(5)
        item.setText(_translate("ServiceMonitorTab", "Request"))
        item = self.service_table.horizontalHeaderItem(6)
        item.setText(_translate("ServiceMonitorTab", "Response"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ServiceMonitorTab = QtWidgets.QWidget()
    ui = Ui_ServiceMonitorTab()
    ui.setupUi(ServiceMonitorTab)
    ServiceMonitorTab.show()
    sys.exit(app.exec())
