# Form implementation generated from reading ui file '/home/addinedu/dev_ws/Shopee/shopee_ros2/src/shopee_main_service/shopee_main_service/dashboard/ui/tab_event_log.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EventLogTab(object):
    def setupUi(self, EventLogTab):
        EventLogTab.setObjectName("EventLogTab")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(EventLogTab)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.log_text_edit = QtWidgets.QTextEdit(parent=EventLogTab)
        self.log_text_edit.setReadOnly(True)
        self.log_text_edit.setObjectName("log_text_edit")
        self.verticalLayout_11.addWidget(self.log_text_edit)

        self.retranslateUi(EventLogTab)
        QtCore.QMetaObject.connectSlotsByName(EventLogTab)

    def retranslateUi(self, EventLogTab):
        pass


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EventLogTab = QtWidgets.QWidget()
    ui = Ui_EventLogTab()
    ui.setupUi(EventLogTab)
    EventLogTab.show()
    sys.exit(app.exec())
