amcl:
  ros__parameters:
    use_sim_time: False
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "base_footprint"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 100.0
    laser_min_range: -1.0
    laser_model_type: "likelihood_field"
    max_beams: 60
    max_particles: 2000
    min_particles: 500
    odom_frame_id: "odom"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    save_pose_rate: 0.5
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 1.0
    update_min_a: 0.2
    update_min_d: 0.25
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05
    scan_topic: scan_filtered
    set_initial_pose: true
    initial_pose: [0, 0, 0]


bt_navigator:
  ros__parameters:
    global_frame: map
    robot_base_frame: base_footprint
    odom_topic: /odom
    bt_loop_duration: 10
    default_server_timeout: 20
    wait_for_service_timeout: 1000
    action_server_result_timeout: 900.0
    navigators: ["navigate_to_pose", "navigate_through_poses"]
    navigate_to_pose:
      plugin: "nav2_bt_navigator::NavigateToPoseNavigator"
    navigate_through_poses:
      plugin: "nav2_bt_navigator::NavigateThroughPosesNavigator"
    # 'default_nav_through_poses_bt_xml' and 'default_nav_to_pose_bt_xml' are use defaults:
    # nav2_bt_navigator/navigate_to_pose_w_replanning_and_recovery.xml
    # nav2_bt_navigator/navigate_through_poses_w_replanning_and_recovery.xml
    # They can be set here or via a RewrittenYaml remap from a parent launch file to Nav2.

    # plugin_lib_names is used to add custom BT plugins to the executor (vector of strings).
    # Built-in plugins are added automatically
    # plugin_lib_names: []

    error_code_names:
      - compute_path_error_code
      - follow_path_error_code

controller_server:
  ros__parameters:
    controller_frequency: 25.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 0.3
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["general_goal_checker"]
    controller_plugins: ["FollowPath"]

    # Progress checker parameters
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0
    
    # Goal checker parameters
    general_goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25

    FollowPath:
      plugin: "nav2_mppi_controller::MPPIController"
      time_steps: 40  # 56 -> 40 긴 예측 시간으로 축소
      model_dt: 0.05
      batch_size: 1000 # 2000 -> 1000 궤적 샘플 계산 지연으로 축소
      vx_std: 0.2
      vy_std: 0.0
      wz_std: 0.2
      vx_max: 0.2
      vx_min: -0.2
      vy_max: 0.0
      wz_max: 1.5
      ax_max: 2.5
      ax_min: -2.5
      ay_min: 0.0
      ay_max: 0.0
      az_max: 3.0
      iteration_count: 1
      prune_distance: 0.6
      transform_tolerance: 0.10 # TF 오차 허용
      temperature: 0.3
      gamma: 0.015
      motion_model: "DiffDrive"
      visualize: false
      reset_period: 1.0 # (only in Humble)
      regenerate_noises: false
      TrajectoryVisualizer:
        trajectory_step: 5
        time_step: 3
      TrajectoryValidator:
        plugin: "mppi::DefaultOptimalTrajectoryValidator"
        collision_lookahead_time: 2.0
        consider_footprint: false
      AckermannConstraints:
        min_turning_r: 0.2
      critics: ["ConstraintCritic", "CostCritic", "GoalCritic", "ObstaclesCritic", "GoalAngleCritic", "PathAlignCritic", "PathFollowCritic", "PathAngleCritic", "PreferForwardCritic", "VelocityDeadbandCritic", "TwirlingCritic"]
      ConstraintCritic:
        enabled: true
        cost_power: 1
        cost_weight: 4.0
      GoalCritic:
        enabled: true
        cost_power: 1
        cost_weight: 6.0
        threshold_to_consider: 1.2
      GoalAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 4.5
        threshold_to_consider: 0.2
      PreferForwardCritic:
        enabled: true
        cost_power: 1
        cost_weight: 3.0
        threshold_to_consider: 0.5
      ObstaclesCritic: # 장애물 충돌 마진
        enabled: true
        cost_power: 1
        repulsion_weight: 1.5              # 1.2 → 1.5로 증가
        critical_weight: 20.0              # 15.0 → 20.0으로 증가
        consider_footprint: true           # false → true (회전 시 footprint 고려)
        collision_cost: 12000.0            # 10000.0 → 12000.0으로 증가
        collision_margin_distance: 0.12    # 0.08 → 0.12로 증가 (안전 마진 확대)
        near_goal_distance: 0.5            # 0.4 → 0.5로 증가
        # inflation_radius: 0.55 # (only in Humble)
        # cost_scaling_factor: 10.0 # (only in Humble)
      CostCritic:
        enabled: true
        cost_power: 1
        cost_weight: 2.5                   # 2.0 → 2.5로 증가
        critical_cost: 150.0               # 200.0 → 150.0으로 감소 (더 엄격)
        consider_footprint: true           # 이미 true로 설정됨
        collision_cost: 600000.0           # 500000.0 → 600000.0으로 증가
        near_goal_distance: 0.6            # 0.8 → 0.6으로 감소
        trajectory_point_step: 2           # 3 → 2로 감소 (더 촘촘한 검사)
      PathAlignCritic:
        enabled: true
        cost_power: 1
        cost_weight: 12.0                  # 10.0 → 12.0으로 증가
        max_path_occupancy_ratio: 0.03     # 0.05 → 0.03으로 감소 (더 엄격)
        trajectory_point_step: 2           # 4 → 2로 감소 (더 촘촘한 검사)
        threshold_to_consider: 0.3         # 0.5 → 0.3으로 감소
        offset_from_furthest: 10           # 15 → 10으로 감소
        use_path_orientations: true        # false → true (경로 방향 고려)
      PathFollowCritic:
        enabled: true
        cost_power: 1
        cost_weight: 8.0      # 이탈시 코스트
        offset_from_furthest: 3 # 경로 추종정도
        threshold_to_consider: 1.0
      PathAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 3.0                   # 2.0 → 3.0으로 증가
        offset_from_furthest: 2            # 4 → 2로 감소
        threshold_to_consider: 0.3         # 0.5 → 0.3으로 감소
        max_angle_to_furthest: 0.8         # 1.0 → 0.8로 감소 (각도 편차 엄격화)
        mode: 1                            # 0 → 1로 변경 (CONSIDER_FEASIBLE_PATH_ORIENTATIONS)
      VelocityDeadbandCritic: # 미세 속도 0으로 죽여서 잔떨림 제거
        enabled: true
        cost_power: 1
        cost_weight: 35.0
        deadband_velocities: [0.03, 0.0, 0.08]   # [vx, vy, wz] 임계값
      TwirlingCritic: # 좌우 불필요한 반복 회전 억제
        enabled: true
        twirling_cost_power: 1
        twirling_cost_weight: 10.0



local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_footprint
      use_sim_time: False
      rolling_window: true
      width: 5
      height: 5
      resolution: 0.05
      footprint: "[[0.3, 0.2], [0.3, -0.2], [-0.3, -0.2], [-0.3, 0.2]]"
      # footprint: '[[0.15, 0.2695], [0.15, -0.2695], [-0.55, -0.2695], [-0.55, 0.2695]]'
      # 반지름 설정 (Global과 동일하게)
      robot_radius: 0.42
      inscribed_radius: 0.20
      circumscribed_radius: 0.42
      inflation_radius: 0.32
      cost_scaling_factor: 5.0
      footprint: "[[0.3, 0.2], [0.3, -0.2], [-0.3, -0.2], [-0.3, 0.2]]"

      plugins: ["voxel_layer", "inflation_layer"]
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 5.0
        inflation_radius: 0.30
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        publish_voxel_map: True
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 2.0
        mark_threshold: 0
        observation_sources: scan
        scan:
          topic: /scan_filtered
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 5.0
          raytrace_min_range: 0.6
          obstacle_max_range: 4.5
          obstacle_min_range: 0.6
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
        inflation_radius: 0.2
      always_send_full_costmap: True

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_footprint
      use_sim_time: False
      robot_radius: 0.25
      resolution: 0.05
      track_unknown_space: true
      # 로봇 크기 설정 (URDF base_link: 0.6 x 0.4)
      footprint: "[[0.3, 0.2], [0.3, -0.2], [-0.3, -0.2], [-0.3, 0.2]]"
      
      # 반지름 설정 수정 
      robot_radius: 0.42                    # 로봇 반지름
      inscribed_radius: 0.20               # 내접원 반지름
      circumscribed_radius: 0.42           # 외접원 반지름
      inflation_radius: 0.32               # 팽창 반지름 (circumscribed_radius보다 커야 함)
      cost_scaling_factor: 3.0             # 비용 스케일링
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan_filtered
        scan:
          topic: /scan_filtered
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.6
          obstacle_max_range: 2.5
          obstacle_min_range: 0.6
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
        inflation_radius: 0.2
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.35
      always_send_full_costmap: True

map_server:
  ros__parameters:
    use_sim_time: False
    # Overridden in launch by the "map" launch configuration or provided default value.
    # To use in yaml, remove the default "map" value in the tb3_simulation_launch.py file & provide full path to map below.
    yaml_filename: ""

map_saver:
  ros__parameters:
    use_sim_time: False
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: True

planner_server:
  ros__parameters:
    expected_planner_frequency: 25.0
    planner_plugins: ["GridBased"]
    costmap_update_timeout: 2.0
    GridBased:
      plugin: "nav2_smac_planner::SmacPlannerHybrid" # In Iron and older versions, "/" was used instead of "::"
      downsample_costmap: false           # whether or not to downsample the map
      downsampling_factor: 1              # multiplier for the resolution of the costmap layer (e.g. 2 on a 5cm costmap would be 10cm)
      tolerance: 0.20                     # dist-to-goal heuristic cost (distance) for valid tolerance endpoints if exact goal cannot be found.
      allow_unknown: true                 # allow traveling in unknown space
      max_iterations: 1000000             # maximum total iterations to search for before failing (in case unreachable), set to -1 to disable
      max_on_approach_iterations: 1000    # Maximum number of iterations after within tolerances to continue to try to find exact solution
      max_planning_time: 3.0              # max time in s for planner to plan, smooth
      motion_model_for_search: "REEDS_SHEPP"    # Hybrid-A* Dubin, Redds-Shepp
      angle_quantization_bins: 72         # Number of angle bins for search
      analytic_expansion_ratio: 3.5       # The ratio to attempt analytic expansions during search for final approach.
      analytic_expansion_max_length: 3.0  # For Hybrid/Lattice nodes: The maximum length of the analytic expansion to be considered valid to prevent unsafe shortcutting
      analytic_expansion_max_cost: 150.0  # 200.0 → 150.0으로 감소 (더 안전한 확장)
      analytic_expansion_max_cost_override: false  #  Whether or not to override the maximum cost setting if within critical distance to goal (ie probably required)
      minimum_turning_radius: 0.30        # 0.35 → 0.30으로 감소 (더 급한 회전 허용)
      reverse_penalty: 2.0                # Penalty to apply if motion is reversing, must be => 1
      change_penalty: 0.1                 # 0.0 → 0.1로 증가 (방향 변경 시 페널티)
      non_straight_penalty: 1.1           # 1.2 → 1.1로 감소 (직진 선호도 완화)
      cost_penalty: 2.5                   # 2.0 → 2.5로 증가 (고비용 영역 회피 강화)
      retrospective_penalty: 0.015
      lookup_table_size: 20.0             # Size of the dubin/reeds-sheep distance window to cache, in meters.
      cache_obstacle_heuristic: True     # Cache the obstacle map dynamic programming distance expansion heuristic between subsequent replannings of the same goal location. Dramatically speeds up replanning performance (40x) if costmap is largely static.
      debug_visualizations: false         # For Hybrid nodes: Whether to publish expansions on the /expansions topic as an array of poses (the orientation has no meaning) and the path's footprints on the /planned_footprints topic. WARNING: heavy to compute and to display, for debug only as it degrades the performance.
      use_quadratic_cost_penalty: False
      downsample_obstacle_heuristic: True
      allow_primitive_interpolation: False
      use_final_approach_orientation: true # 최종 접근 시 방향 정렬
      allow_reverse_expansion: True          # 필요시 후진 확장 허용
      coarse_search_resolution: 4         # Number of bins to skip when doing a coarse search for the path. Only used for all_direction goal heading mode.
      goal_heading_mode: "ALL_DIRECTION"        # DEFAULT, BIDIRECTIONAL, ALL_DIRECTION
      smooth_path: True                   # If true, does a simple and quick smoothing post-processing to the path

      smoother:
        max_iterations: 1000
        w_smooth: 0.3
        w_data: 0.2
        tolerance: 1.0e-10
        do_refinement: true
        refinement_num: 2

smoother_server:
  ros__parameters:
    use_sim_time: False
    smoother_plugins: ["simple_smoother"]
    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 1.0e-10
      max_its: 1000
      do_refinement: True

behavior_server:
  ros__parameters:
    robot_base_frame: base_footprint      # base_link → base_footprint로 변경
    local_costmap_topic: local_costmap/costmap_raw
    global_costmap_topic: global_costmap/costmap_raw
    local_footprint_topic: local_costmap/published_footprint
    global_footprint_topic: global_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins: ["spin", "backup", "drive_on_heading", "assisted_teleop", "wait"]
    spin:
      plugin: "nav2_behaviors::Spin"
    backup:
      plugin: "nav2_behaviors::BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors::DriveOnHeading"
    wait:
      plugin: "nav2_behaviors::Wait"
    assisted_teleop:
      plugin: "nav2_behaviors::AssistedTeleop"
    local_frame: odom
    global_frame: map

    transform_tolerance: 0.1
    simulate_ahead_time: 2.0
    max_rotational_vel: 0.8               # 1.0 → 0.8로 감소
    min_rotational_vel: 0.4
    rotational_acc_lim: 2.5          git     # 3.2 → 2.5로 감소

robot_state_publisher:
  ros__parameters:
    use_sim_time: False

waypoint_follower:
  ros__parameters:
    use_sim_time: False
    loop_rate: 20
    stop_on_failure: false
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 200

velocity_smoother:
  ros__parameters:
    use_sim_time: False
    smoothing_frequency: 30.0
    scale_velocities: False
    feedback: "CLOSED_LOOP"
    max_velocity: [0.15, 0.0, 0.8]       # [0.2, 0.0, 1.2] → 속도 제한 (안정성 우선)
    min_velocity: [-0.1, 0.0, -1.2]     # [-0.25, 0.0, -1.0] → 각속도 한계 완화
    max_accel: [1.5, 0.0, 2.0]           # [2.0, 0.0, 2.5] → 가속도 제한 (급격한 변화 억제)
    max_decel: [-1.8, 0.0, -2.0]
    odom_topic: "odom"
    odom_duration: 0.05                   # 0.1 → 0.05로 감소 (더 빠른 반응)
    deadband_velocity: [0.02, 0.0, 0.05] # [0.0, 0.0, 0.0] → 미세 진동 억제